server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/a_yard
    username: root
    password: 151116
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true