server:
  port: 8080
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ayard
    username: tber
    password: 123456
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    
  jpa:
    hibernate:
      ddl-auto: update